name: Pre-Merge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: [ '8.2', '8.3' ]
    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:2.7

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ matrix.operating-system }}-php-${{ matrix.php-version }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH  }}

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Run Pint
        run: vendor/bin/pint app --test

      - name: Run Psalm
        run: vendor/bin/psalm "--config=./psalm.xml" "--no-cache" "--memory-limit=2560M" "--threads=1"
